### PR TITLE
Remove /vagrant paths and assume the module is installed first

### PR DESCRIPTION
**Pull request by jeffmccune**
The behavior without this patch is that step1 assumed it was running
from my personal development location of /vagrant/modules.

We're now going to assume the first thing a customer does is install
this module into their module path.  As a result, we no loner should try
and install the module in step2.  This part of step2 is removed by this
patch.

Furthermore, there is no longer a need to hard code any paths since it's
all either a single script or a puppet manifest itself.

### CODE REVIEW

**Comment by nigelkersten** [comment]
Is it absolutely safe to install this module in the modulepath (and have agents pick up facts etc) before running any of the server-side steps by hand?

**Comment by jeffmccune** [comment]
@nigelkersten

Yes, the module is safe if added to modulepath.  The facts may collide with other facts, but none of the plugins synchronized make any changes to the system.

**Comment by jeffmccune** [comment]
Rebasing on master, please don't comment on 485c46a as it will disappear from this pull req.

-Jeff

**Comment by jeffmccune** [comment]
Rebased and ready for review.

**Pull request merged**
